# Generated by Django 2.2.7 on 2019-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191116_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='listed_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
