# Generated by Django 2.2.7 on 2019-11-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191113_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='voting',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
