# Generated by Django 2.2.6 on 2019-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20191021_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('color', 'product')},
        ),
    ]
